### ISSUE TITLE
Keys aren't listed properly

### ISSUE THREAD

**Issue by kenorb** [FunctionX/fx-core#25]
I've installed the latest master version and my keys are no longer listed.

```
$ fxcored keys list
[]
```

Although I can still see them when specifying 'test' for a backend manually:

```
fxcored keys --keyring-backend test list
- name: ...
...
```

This is also not expected:

```
$ fxcored keys add foobar

- name: foobar
  type: local
...

$ fxcored keys list
[]

$ fxcored keys add foobar
override the existing name foobar [y/N]: 

$ fxcored keys list foobar
[]

$ fxcored keys delete foobar
Error: The specified item could not be found in the keyring
```

It's there, but it doesn't show in the list, and it's not possible to delete it. Also when trying to send the transaction using `tx bank send`, it's not finding the key.

**Comment by zakir-code** [comment]
We also found this problem because of the addition of the `.fxcore/config/client.toml` configuration file.

**Comment by zakir-code** [comment]
fixed on 46a91e9c6dc16ed590dbc608451a83dfa067f04f

**Comment by kenorb** [comment]
Still happening in `functionx/fx-core:dhobyghaut-1.1` container. I can't check which which version it is due to GH-37.

```
$ fxcored keys add test1
Enter keyring passphrase:
```

I need to explicitly set `--keyring-backend test` during add and list, despite help page is showing "test" backend as default.

Is version in dhobyghaut-1.1 contains fix, or not yet? Or it's some kind of regression?

**Comment by zakir-code** [comment]
fixed on `docker run --rm functionx/fx-core:dhobyghaut-1.1 version`
`testnet-evm-651559e733569514ee66fa490f238ff1822384ed`
